// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcBruker.Data;

#nullable disable

namespace TSD2491_oblig_1_261660.Migrations
{
    [DbContext(typeof(BrukerContext))]
    [Migration("20250415065747_LeggTilAntallSpill")]
    partial class LeggTilAntallSpill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("TSD2491_oblig_1_261660.Models.Bruker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntallSpill")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kontakt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bruker");
                });
#pragma warning restore 612, 618
        }
    }
}
